# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 19:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailChimpUser',
            fields=[
                ('chimp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mailchimp_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('access_token', models.CharField(max_length=64, null=True)),
                ('metadata', jsonfield.fields.JSONField(null=True)),
            ],
            options={
                'db_table': 'mailchimp_user',
            },
        ),
    ]
